- hosts: woo
  sudo: yes
  roles:
      - ansible-nginx
      - ansible-role-mysql
      - ubuntuphpfpm7
      - installwordpress

  vars:
     nginx_version: 1.8.1

  handlers:
     - name: restart nginx
       service: name=nginx state=restarted